-- DBUPDATE-031-0.SQL
create table T_LOGIN_REQUEST ( LR_ID_C varchar(36) not null, LR_TOKEN_C varchar(100) not null, LR_IP_C varchar(45) not null, LR_TIMESTAMP_D datetime not null, LR_STATUS_C varchar(20) not null, primary key (LR_ID_C) );

-- Insert a new setting for OCR recognition
insert into T_CONFIG (CFG_ID_C, CFG_VALUE_C) values ('OCR_ENABLED', 'true');

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '31' where CFG_ID_C = 'DB_VERSION';

CREATE TABLE T_USER_ACTIVITY (
    UTA_ID_C VARCHAR(36) NOT NULL,
    UTA_IDUSER_C VARCHAR(36) NOT NULL,
    UTA_ACTIVITY_TYPE_C VARCHAR(50) NOT NULL,
    UTA_ENTITY_ID_C VARCHAR(36),
    UTA_PROGRESS_N INT NOT NULL DEFAULT 0,
    UTA_PLANNED_DATE_D TIMESTAMP,
    UTA_COMPLETED_DATE_D TIMESTAMP,
    UTA_CREATEDATE_D TIMESTAMP NOT NULL,
    UTA_DELETEDATE_D TIMESTAMP,
    PRIMARY KEY (UTA_ID_C)
);

-- Add foreign key constraint
ALTER TABLE T_USER_ACTIVITY 
ADD CONSTRAINT FK_UTA_IDUSER_C 
FOREIGN KEY (UTA_IDUSER_C) 
REFERENCES T_USER (USE_ID_C) 
ON DELETE RESTRICT 
ON UPDATE RESTRICT;

-- Create composite indexes
CREATE INDEX IDX_UTA_USER_ACTIVITY ON T_USER_ACTIVITY (UTA_IDUSER_C, UTA_ACTIVITY_TYPE_C);
CREATE INDEX IDX_UTA_DATES ON T_USER_ACTIVITY (UTA_CREATEDATE_D, UTA_PLANNED_DATE_D, UTA_COMPLETED_DATE_D);
